# Generated by Django 4.2.4 on 2023-09-05 13:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/logos",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "logo_negatif",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/slides",
                        verbose_name="Logo négatif",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/logos",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=50, verbose_name="Titre"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=50, verbose_name="Adresse"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=50, verbose_name="email de l'entreprise"
                    ),
                ),
                (
                    "email2",
                    models.EmailField(
                        blank=True,
                        max_length=50,
                        verbose_name="2eme email de l'entreprise",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="numéro de téléphone de l'entreprise",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="2eme numéro de téléphone de l'entreprise",
                    ),
                ),
                (
                    "about",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Text a propos"
                    ),
                ),
                (
                    "conditions",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Conditions utilisations"
                    ),
                ),
                (
                    "mini_about",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Petit texte a propos de l'entreprise ( bas de page)",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Lien page Facebook",
                    ),
                ),
                (
                    "insta",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Lien page Instagram",
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Lien Compte Twitter",
                    ),
                ),
                (
                    "google_plus",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Lien Compte Google plus",
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Lien Chaine Youtube",
                    ),
                ),
                (
                    "chat_code",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Script messagerie instantané",
                    ),
                ),
                (
                    "pixel",
                    models.TextField(
                        blank=True, null=True, verbose_name="Script Facebook pixel"
                    ),
                ),
                (
                    "analytics",
                    models.TextField(
                        blank=True, null=True, verbose_name="Script Analytics"
                    ),
                ),
                (
                    "contact_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contact message"
                    ),
                ),
                (
                    "google_maps",
                    models.TextField(
                        blank=True, null=True, verbose_name="iframe google maps"
                    ),
                ),
            ],
            options={
                "verbose_name": "1- Infomation",
                "verbose_name_plural": "1- Infomations",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du magasin"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="numéro de téléphone du magasin",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Adresse"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Store principale"),
                ),
            ],
        ),
    ]
