# Generated by Django 4.2.5 on 2023-09-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Store",
        ),
    ]
