# Generated by Django 4.2.5 on 2023-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description '),
        ),
        migrations.AddField(
            model_name='business',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO keywords'),
        ),
        migrations.AddField(
            model_name='business',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='business',
            name='work_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='business',
            name='work_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
