# Generated by Django 4.2.5 on 2023-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_work_end_alter_business_work_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='insta',
            new_name='instagram',
        ),
        migrations.RemoveField(
            model_name='business',
            name='google_plus',
        ),
        migrations.AddField(
            model_name='business',
            name='linkedin',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte linkedin'),
        ),
        migrations.AddField(
            model_name='business',
            name='tiktok',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Tiktok'),
        ),
        migrations.AlterField(
            model_name='business',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte Twitter (X)'),
        ),
    ]
