# Generated by Django 4.2.2 on 2023-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_business_about_af_remove_business_about_ar_dz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='mini_about_ar',
            field=models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)"),
        ),
        migrations.AddField(
            model_name='business',
            name='mini_about_en',
            field=models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)"),
        ),
        migrations.AddField(
            model_name='business',
            name='mini_about_fr',
            field=models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)"),
        ),
    ]
